apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: library
    service: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
      service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: library
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - library_user
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - library_user
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc 